trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: Creating a vnet
  inputs:
    azureSubscription: 'Azure portal'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './b-session-7/vnets.sh'
    arguments: '-g automated-bash-group -l ukwest -n automated-bash-vnet -a 10.0.0.0/16 -s subnet1 10.0.0.0/24 subnet2 10.0.1.0/24'

- task: AzureCLI@2
  displayName: Create NSG
  inputs:
    azureSubscription: 'Azure portal'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './b-session-7/nsg.sh'
    arguments: '-l ukwest -n automated-bash-nsg -rn AllowAll -r Allow Outbount Tcp'

- task: AzureCLI@2
  displayName: Assign NSG
  inputs:
    azureSubscription: 'Azure portal'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './b-session-7/assigns.sh'
    arguments: '-nn automated-bash-nsg -vn automated-bash-vnet -s subnet1'
    

- task: AzureCLI@2
  displayName: Create a VM
  inputs:
    azureSubscription: 'Azure portal'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './b-session-7/vm.sh'
    arguments: '-g automated-bash-group -vmn auto-vm-01 -i Canonical:UbuntuServer:18.04-LTS:latest -si Standard_DS1_v2 -st Standard_LRS -v automated-bash-vnet -su subnet1 -d somednsname -r reservedIP'